name: simple-mini-github
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        uses: ocaml/setup-ocaml@v2
      - run: opam install . --deps-only
      - run: rm -rf repos/
      - run: dune build
